# Generated by Django 6.0.7 on 2026-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipe_description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='Home/recipe_images/')),
            ],
        ),
    ]
