# Generated by Django 6.0.7 on 2026-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_vegetable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='recipe_image',
            field=models.ImageField(upload_to='recipe_images/'),
        ),
    ]
